[1] "Error in { : \n  task 493 failed - \"illegal input in lagvalue - lag, 12.2951, too large, at time = 14.2951\n\"\nCalls: ga_verbose -> %DO% -> do.call -> %dopar% -> <Anonymous>\n"

[1] "Error in h(simpleError(msg, call)) : \n  error in evaluating the argument 'x' in selecting a method for function 'print': object 'ga_res' not found\nCalls: print -> .handleSimpleError -> h\n"

